hcqmarketing/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls',)),
    path('', include('suppliers.urls',)),
    path('', include('customers.urls',)),
    path('', include('products.urls',)),
    path('', include('purchases.urls')),
    path('', include('sales.urls')),
    path('', include('employees.urls')),
    path('inventory/', include('inventory.urls')),
]

index/urls.py
from django.urls import path 
from .import views

urlpatterns = [
    path('', views.index, name = 'index'),
    
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.inventory_index, name='inventory_index'),  # URL for inventory index page
    path('<int:product_id>/', views.product_detail, name='product_detail'),
]

purchases/urls.py
from django.urls import path
from . import views

app_name = 'purchases'

urlpatterns = [
    path('purchases/', views.purchase_index, name='purchase_index'),
    path('add/', views.add_purchase, name='add_purchase'),
    path('change_status/<int:id>/', views.change_purchase_status, name='change_purchase_status'),
    path('<int:purchase_id>/', views.purchase_detail, name='purchase_detail'),
    path('<int:purchase_id>/add_invoice/', views.add_invoice, name='add_invoice'),
    path('returns/', views.purchase_return_list, name='purchase_return_list'),
    path('returns/create/', views.create_purchase_return, name='create_purchase_return'),
    path('export_csv/', views.export_purchases_csv, name='export_purchases_csv'),
    path('export_pdf/', views.export_purchases_pdf, name='export_purchases_pdf'),
]

index/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>HCQ MARKETING</title>
    <link href="{% static 'css/custom-styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body class="d-flex flex-column min-vh-100" style="background-color: #fcfcfc;">
    <nav class="navbar navbar-expand-lg" style="background-color: #262626;" data-bs-theme="dark">
        <div class="container-fluid justify-content-center">
            <a class="navbar-brand" href="{% url 'index' %}">HCQ MARKETING</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse flex-grow-0" id="navbarColor01">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'employees_index' %}active{% endif %}" href="{% url 'employees_index' %}">Employees</a>
                    </li>
            
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'suppliers_index' %}active{% endif %}" href="{% url 'suppliers_index' %}">Suppliers</a>
                    </li>
            
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'customers_index' %}active{% endif %}" href="{% url 'customers_index' %}">Customers</a>
                    </li>
            
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sales</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'sales_list' %}">Sales</a>
                            <a class="dropdown-item" href="{% url 'create_sale' %}">New Sales</a>
                            <a class="dropdown-item" href="#">Sales Return</a>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'products_index' %}active{% endif %}" href="{% url 'products_index' %}">Products</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% if request.resolver_match.url_name == 'purchase_index' or request.resolver_match.url_name == 'create_purchase_return' or request.resolver_match.url_name == 'purchase_return_list' %}active{% endif %}" 
                           data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Purchases
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item {% if request.resolver_match.url_name == 'purchase_index' %}active{% endif %}" href="{% url 'purchases:purchase_index' %}">Purchase Records</a>
                            <a class="dropdown-item {% if request.resolver_match.url_name == 'create_purchase_return' %}active{% endif %}" href="{% url 'purchases:create_purchase_return' %}">Return Purchase</a>
                            <a class="dropdown-item {% if request.resolver_match.url_name == 'purchase_return_list' %}active{% endif %}" href="{% url 'purchases:purchase_return_list' %}">Purchase Return List</a>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'inventory_index' %}active{% endif %}" href="{% url 'inventory:inventory_index' %}">Inventory</a>
                    </li>
            
                </ul>
            </div>            
        </div>   
    </nav>

    <div class="container-fluid">
        {% block body %}
        {% endblock %}
    </div>

    <footer class="mt-auto mb-4">
        <div class="text-center">
            <span>HCQ MARKETING</span>
            <h6>2024</h6>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

index/templates/index.html
{% extends "base.html" %}

{% block body %}

{% if messages %}
<div class="alert alert-success">
    {% for message in messages %}
        {{ message }}
    {% endfor %}
</div>
{% endif %}

<h3 class = "m-4">Dashboard</h3>
<div class = "row">
    <div class = "col-12">
        {% if index %}
        <div class="card bg-light ms-4 me-4 mb-4">
            <div class="card-header"></div>
            <div class="card-body">
                <p class="card-text">
                    <div class ="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">First Name</th>
                                <th scope="col">Last Name</th>
                                <th scope="col">Supplier Hardware</th>
                                <th scope="col">Email</th>
                                <th scope="col">Address</th>
                                <th scope="col">Contact</th>
                                <th scope="col">Date Started</th>
                                
                            </tr>
                            </thead>
                            <tbody>
                                {% for supplier in suppliers %}
                                    <tr>
                                        <td>{{ supplier.id}}</td>
                                        <td>{{ supplier.first_name}}</td>
                                        <td>{{ supplier.last_name}}</td>
                                        <td>{{ supplier.supplier_hardware}}</td>
                                        <td>{{ supplier.email}}</td>
                                        <td>{{ supplier.address}}</td>
                                        <td>{{ supplier.contact_num}}</td>
                                        <td>{{ supplier.dateStart}}</td>



                                        
                                        
                                        
                                    </tr> 
                                    
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </p>
            </div>
        </div>

        {% else %}
            <h5 class = "alert alert-primary ms-4 me-4"> No Records </h5>
        {% endif %}
    </div>
</div> 
</div>

<script>
    function confirmDelete() {
        return confirm("Are you sure you want to delete this supplier?");
    }
</script>

{% endblock %}